name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SquaremapPlayers.jar
          path: build/libs/SquaremapPlayers-*.jar